apiVersion: v1
kind: Namespace
metadata:
    name: ci
    labels:
        name: ci
---
apiVersion: v1
kind: Namespace
metadata:
    name: cd
    labels:
        name: cd
---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: ci
    annotations:
        kubernetes.io/change-cause: "Start Backend Deploy and svc"  
    name: deploy-backendgo
    labels:
        app: backendgo
spec: 
    replicas: 3
    selector:
        matchLabels:
            app: backendgo
    template:
        metadata:
            labels:
                app: backendgo
        spec:
            containers:
            -   name: backendgo-cont
                image: jhonzp/k8s-hands-on-bk:v2
                imagePullPolicy: IfNotPresent        
---
#Services DNS= svcname + nsName + svc.cluster.local
apiVersion: v1
kind: Service
metadata:
    name: service-backendgo
    namespace: ci
    labels:
        app: backendgo
spec:  
    selector:
        app: backendgo
    ports:
    -   name: http
        protocol: TCP
        port: 9090
        targetPort: 9090