apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
---
apiVersion: v1
kind: LimitRange
metadata:
  name: min-max
  namespace: prod
spec:
  limits:
  - max:
      memory: 1Gi
      cpu: 1
    min:
      memory: 100Mi
      cpu: 100m
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest3
  namespace: prod
  labels:
    app: backend
    env: prod
spec:
  containers:
  - name: cont1
    image: nginx:alpine 
    resources:
      limits:
        cpu: 2
        memory: 50Mi
      requests:
        cpu: 0.3
        memory: 50Mi