apiVersion: v1
kind: Namespace
metadata:
  name: uat
  labels:
    name: uat
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-test
  namespace: uat
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: uat
  annotations:
    kubernetes.io/change-cause: "Changes port to 110"  
  name: deploy-rq
  labels:
    app: front
spec: 
  replicas: 4
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 110
        resources:
            requests:
                memory: 500Mi
                cpu: 500m
            limits:
                memory: 800Mi
                cpu: 1                