apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\DEV\Install\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs
  name: nodejs
spec:
  ports:
  - name: "8085"
    port: 8085
    targetPort: 8080
  selector:
    io.kompose.service: nodejs
status:
  loadBalancer: {}
