version: '3'
services: 
    redis-server:
        image: 'redis'
        ports: 
            - "6378:6379"        
    node-app:
        ##Policy restart ("no", always, on-failure,unless-stopped)
        build: .
        restart: always
        ports: 
            - "4001:8081"
        depends_on: 
            - redis-server
     