apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Changes port to 110"  
  name: deployment-test
  labels:
    app: front
spec: 
  replicas: 5
  selector:
    matchLabels:
      app: pod-label2
  template:
    metadata:
      labels:
        app: pod-label2
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 110