#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Start frontend Deploy and svc"  
  name: deploy-frontend
  labels:
    app: frontend
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-cont
        image: jhonzp/k8s-hands-on-f:v3
        imagePullPolicy: IfNotPresent        
---
#Services
apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  labels:
    app: frontend
spec:
  type: NodePort  
  selector:
    app: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80