apiVersion: v1
kind: Secret
metadata:
  name: secretenv
type: Opaque
stringData:
  USER_NAME: test1
  PASSWORD: "test1234"
---
apiVersion: v1
kind: Pod
metadata:
  name: env-pod
spec:
  containers:
  - name: mycontainer
    image: nginx:alpine
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: secretenv
            key: USER_NAME
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secretenv
            key: PASSWORD