apiVersion: v1
kind: Secret
metadata:
  name: secret1
type: Opaque
stringData:
  USER_NAME: test1
  PASSWORD: "test1234"
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    volumeMounts:
    - name: voltest
      mountPath: "/opt"
      readOnly: true
  volumes:
  - name: voltest
    secret:
      secretName: secret1
      items:
      - key: USER_NAME
        path: user.txt